window.PLG_PROPERTIES = [
  {
    id: "puerta-del-sol-sps",
    slug: "puerta-del-sol-sps",
    title: "Casa Mediterranea de Lujo",
    country: "Honduras",
    city: "San Pedro Sula",
    neighborhood: "Residencial Puerta Del Sol",
    transaction: "rent",
    transactionLabel: "En Renta",
    propertyType: "house",
    propertyTypeLabel: "Casa",
    currency: "USD",
    price: 2300,
    priceLabel: "USD 2300/mes",
    beds: 4,
    baths: 5,
    areaM2: 480,
    thumbnail: "./imagenes/yellowHouse.jpeg",
    detailUrl: "./house-detail.html",
    published: true,
    paidActive: true
  },
  {
    id: "portal-del-bosque-2-tgu",
    slug: "portal-del-bosque-2-tgu",
    title: "Casa Moderna en Portal del Bosque 2",
    country: "Honduras",
    city: "Tegucigalpa",
    neighborhood: "Portal del Bosque 2",
    transaction: "rent",
    transactionLabel: "En Renta",
    propertyType: "house",
    propertyTypeLabel: "Casa",
    currency: "USD",
    price: 1180,
    priceLabel: "USD 1180/mes",
    beds: 3,
    baths: 4,
    areaM2: 180,
    thumbnail: "./imagenes/portaldelbosque/portalHouseFachada.png",
    detailUrl: "./housePortal.html",
    published: true,
    paidActive: true
  }
];
